import { FlatType } from "../components/Flats/FlatsType";

export const flats: Array<FlatType> = [
  {
    id: 1,
    miestas: "Vilnius",
    kaina: 200000,
    plotas: 50,
    plotoVienetas: "m2",
    kambariuSkaicius: 3,
  },
  {
    id: 2,
    miestas: "Kaunas",
    kaina: 300000,
    plotas: 80,
    plotoVienetas: "m2",
    kambariuSkaicius: 5,
  },
  {
    id: 3,
    miestas: "Alytus",
    kaina: 55000,
    plotas: 75,
    plotoVienetas: "m2",
    kambariuSkaicius: 4,
  },
  {
    id: 4,
    miestas: "Vilnius",
    kaina: 155000,
    plotas: 75,
    plotoVienetas: "m2",
    kambariuSkaicius: 4,
  },
  {
    id: 5,
    miestas: "Klaipeda",
    kaina: 170000,
    plotas: 75,
    plotoVienetas: "m2",
    kambariuSkaicius: 3,
  },
  {
    id: 6,
    miestas: "Nida",
    kaina: 2000000,
    plotas: 52,
    plotoVienetas: "m2",
    kambariuSkaicius: 4,
  },
  {
    id: 7,
    miestas: "Klaipeda",
    kaina: 250000,
    plotas: 100,
    plotoVienetas: "m2",
    kambariuSkaicius: 3,
  },
  {
    id: 8,
    miestas: "Jonava",
    kaina: 100000,
    plotas: 75,
    plotoVienetas: "m2",
    kambariuSkaicius: 4,
  },
  {
    id: 9,
    miestas: "Šiauliai",
    kaina: 350000,
    plotas: 70,
    plotoVienetas: "m2",
    kambariuSkaicius: 4,
  },
  {
    id: 10,
    miestas: "Panevėžys",
    kaina: 100000,
    plotas: 60,
    plotoVienetas: "m2",
    kambariuSkaicius: 3,
  },
  {
    id: 11,
    miestas: "Pakruojis",
    kaina: 72000,
    plotas: 68,
    plotoVienetas: "m2",
    kambariuSkaicius: 4,
  },
  {
    id: 12,
    miestas: "Naujoji Akmenė",
    kaina: 30000,
    plotas: 70,
    plotoVienetas: "m2",
    kambariuSkaicius: 3,
  },
];
